/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import Controller.ActionsOneExercise;
import Interface.Canvas;
import Interface.TortueCouleur;
import Interface.TortueG;
import Interface.TortueRapide;
import turtle_project_hci.Exercise;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Utilisateur
 */
public class CreateOneExercise extends JFrame{


    private TortueG newTurtle, normalTurtle;
    private TortueCouleur colorTurtle;
    private TortueRapide fastTurtle;
    private JButton normal, color, fast, write, unwrite, speedUp, slowDown;
    private JButton forward, backward, left, right, move, restart, save;
    private JPanel panelArrows, panelLabel, panelMode, panelButtonsRight, panelRight, panelPage;
    private JLabel myEmptyLabel, labelInstruction, labelMode;
    private JFrame myFrame, secondFrame, thirdFrame;
    private String result=""; //code generated by the creation of the exercise

    // for the second frame
    private JLabel colorLabel, fastLabel;
    private JButton black, red, blue, green, yellow, magenta, setSpeed;
    private JPanel panelColor, panelGlobal, panelGlobal2, panelRadioButtons, canv;
    private JComboBox comboSpeed;
    private JRadioButton check1Bis, check2Bis, check3Bis, check4Bis, check5Bis;
    
    private Exercise ex;
    
    
    public void press(ActionEvent ae) {
        if (ae.getSource() == forward){
            while (newTurtle.getDirection()!=3){
                newTurtle.tourner();
            }
            result += "T"; //top
        }else if (ae.getSource() == left) {
            while (newTurtle.getDirection()!=2){
                newTurtle.tourner();

            }
            result += "L"; //left
        }else if (ae.getSource() == right){
            while (newTurtle.getDirection()!=0){
                newTurtle.tourner(); 

            }
            result += "R"; //right
        }else if (ae.getSource()==backward){
            while (newTurtle.getDirection()!=1){
                newTurtle.tourner();
            }
            result += "B"; //bottom
        }else if (ae.getSource()==unwrite){
            newTurtle.tracer(false);
            result += "U"; //unwrite

        }else if (ae.getSource()==write){
            newTurtle.tracer(true);
            result+="W"; //write
        }else if (ae.getSource()== normal){
            newTurtle = normalTurtle;
            ex.setModeC(null);
            ex.setModeG(newTurtle);
            ex.setModeR(null);
            speedUp.setEnabled(false);
            slowDown.setEnabled(false);
            newTurtle.reset();
            result = "";

        }else if (ae.getSource()== color){
            newTurtle = colorTurtle;
            //ex.setModeC(newTurtle);
            ex.setModeG(null);
            ex.setModeR(null);
            speedUp.setEnabled(false);
            slowDown.setEnabled(false);
            newTurtle.reset();
            result = "";
            chooseMode(colorTurtle);
            
        }else if (ae.getSource()== fast){
            newTurtle = fastTurtle;
            ex.setModeC(null);
            ex.setModeG(null);
            ex.setModeR(fastTurtle);
            speedUp.setEnabled(true);
            slowDown.setEnabled(true);
            newTurtle.reset();
            result = "";
            chooseMode(fastTurtle);

        }else if (ae.getSource()== move){
            newTurtle.avancer();
            result += "M"; //move

        }else if (ae.getSource()== restart){
            newTurtle.reset();
            result ="";
        } else if (ae.getSource()==black){
            newTurtle = new TortueCouleur("black");
            ex.setModeC(new TortueCouleur("black"));
            secondFrame.dispose();
        } else if (ae.getSource()==red){
            newTurtle = new TortueCouleur("red");
            ex.setModeC(new TortueCouleur("red"));
            secondFrame.dispose();
        } else if (ae.getSource()==blue){
            newTurtle = new TortueCouleur("blue");
            ex.setModeC(new TortueCouleur("blue"));
            secondFrame.dispose();
        } else if (ae.getSource()==green){
            newTurtle = new TortueCouleur("green");
            ex.setModeC(new TortueCouleur("green"));
            secondFrame.dispose();
        } else if (ae.getSource()==yellow){
            newTurtle = new TortueCouleur("yellow");
            ex.setModeC(new TortueCouleur("yellow"));
            secondFrame.dispose();
        } else if (ae.getSource()==magenta){
            newTurtle = new TortueCouleur("magenta");
            ex.setModeC(new TortueCouleur("magenta"));
            secondFrame.dispose();
        } else if (ae.getSource()==setSpeed){
            if (check1Bis.isSelected()){
                fastTurtle.setVitesse(1);
                newTurtle = fastTurtle;
            }else if (check2Bis.isSelected()){
                fastTurtle.setVitesse(2);
                newTurtle = fastTurtle;
            }else if (check3Bis.isSelected()){
                fastTurtle.setVitesse(3);
                newTurtle = fastTurtle;
            }else if (check4Bis.isSelected()){
                fastTurtle.setVitesse(4);
                newTurtle = fastTurtle;
            }else if (check5Bis.isSelected()){
                fastTurtle.setVitesse(5);
                newTurtle = fastTurtle;
            }
            thirdFrame.dispose();

        }else if (ae.getSource()==speedUp){
            fastTurtle.accelerer();
            result += "A"; //acceler
            
        }else if (ae.getSource()==slowDown){
            fastTurtle.ralentir();
            result += "F"; //freiner
        }else if (ae.getSource()==save){
            ex.setCodeExercise(result);
            //labelInstruction.setText(ex.getCodeExercise());
            //myFrame.dispose();

        }
    }
    

    /**public void saveGraph() throws IOException {
        BufferedImage outImage=new BufferedImage(canv.getWidth(),canv.getHeight(),BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics=outImage.createGraphics();
        canv.paint(graphics);
        graphics.dispose();
        File outFile=new File("newTurtle.png");
        ImageIO.write(outImage,"png",outFile);
        try {
            if (!ImageIO.write(outImage,"png",outFile))
                System.out.println("Format d'écriture non pris en charge" );
        } catch (Exception e) {
            System.out.println("erreur dans l'enregistrement de l'image :" );
            e.printStackTrace();
        }
    }*/
    
    public void chooseMode(TortueG mode){
        if (mode==colorTurtle){
            colorLabel = new JLabel("Choose a color for your Color Turtle:");
                        
            panelColor = new JPanel();
            panelColor.setLayout(new GridLayout(1,6));
            panelColor.add(black);
            panelColor.add(red);
            panelColor.add(blue);
            panelColor.add(green);
            panelColor.add(yellow);
            panelColor.add(magenta);
            
            panelGlobal = new JPanel();
            panelGlobal.setLayout(new GridLayout(2,1));
            panelGlobal.add(colorLabel);
            panelGlobal.add(panelColor);
            
            secondFrame = new JFrame();

            secondFrame.add(panelGlobal);
            secondFrame.setResizable(true);
            secondFrame.pack();
            secondFrame.setVisible(true);
            
        }else if (mode==fastTurtle){
            fastLabel = new JLabel("Set the initial speed of your turtle:");
            
            check1Bis = new JRadioButton("1");
            check2Bis = new JRadioButton("2");
            check3Bis = new JRadioButton("3");
            check4Bis = new JRadioButton("4");
            check5Bis = new JRadioButton("5");
            panelRadioButtons = new JPanel();
            panelRadioButtons.add(check1Bis);
            panelRadioButtons.add(check2Bis);
            panelRadioButtons.add(check3Bis);
            panelRadioButtons.add(check4Bis);
            panelRadioButtons.add(check5Bis);
            
            
            panelGlobal2 = new JPanel();
            panelGlobal2.setLayout(new GridLayout(3,1));
            panelGlobal2.add(fastLabel);
            panelGlobal2.add(panelRadioButtons);
            panelGlobal2.add(setSpeed);
            
            thirdFrame = new JFrame();
            
            thirdFrame.add(panelGlobal2);
            thirdFrame.setResizable(true);
            thirdFrame.pack();
            thirdFrame.setVisible(true);

        }
    }

    
    public CreateOneExercise(Exercise ex){
        ActionsOneExercise aoe = new ActionsOneExercise(this);
        
        this.ex = ex;
        
        normalTurtle = new TortueG();
        colorTurtle = new TortueCouleur();
        fastTurtle = new TortueRapide();
                
        //exo = new Exercise();
        newTurtle = normalTurtle; //set the newTurtle by default
        
        
        normal = new JButton("Graphical Turtle");
        normal.addActionListener(aoe);
        
        color = new JButton("Color Turtle");
        color.addActionListener(aoe);
        
        fast = new JButton("Fast Turtle");
        fast.addActionListener(aoe);
        
        forward = new JButton(new ImageIcon(getClass().getResource("/images/arrowN.png")));
        forward.addActionListener(aoe);
        
        backward = new JButton(new ImageIcon(getClass().getResource("/images/arrowS.png")));
        backward.addActionListener(aoe);
        
        left = new JButton(new ImageIcon(getClass().getResource("/images/arrowW.png")));
        left.addActionListener(aoe);
        
        right = new JButton(new ImageIcon(getClass().getResource("/images/arrowE.png")));
        right.addActionListener(aoe);
        
        move = new JButton("Move");
        move.addActionListener(aoe);
        
        restart = new JButton("Restart");
        restart.addActionListener(aoe);
        
        write = new JButton("Write");
        write.addActionListener(aoe);
        
        unwrite = new JButton("Unwrite");
        unwrite.addActionListener(aoe);
        
        speedUp = new JButton("Speed Up");
        speedUp.addActionListener(aoe);
        speedUp.setEnabled(false);
        
        slowDown = new JButton("Slow Down");
        slowDown.addActionListener(aoe);
        slowDown.setEnabled(false);
        
        save = new JButton("Save");
        save.addActionListener(aoe);
        
        black = new JButton(new ImageIcon(getClass().getResource("/images/blackcolor_opt.png")));
        black.addActionListener(aoe);
        
        red = new JButton(new ImageIcon(getClass().getResource("/images/red_opt.png")));
        red.addActionListener(aoe);

        blue = new JButton(new ImageIcon(getClass().getResource("/images/blue_opt.png")));
        blue.addActionListener(aoe);
            
        green = new JButton(new ImageIcon(getClass().getResource("/images/green_opt.png")));
        green.addActionListener(aoe);
            
        yellow = new JButton(new ImageIcon(getClass().getResource("/images/yellow_opt.jpg")));
        yellow.addActionListener(aoe);
            
        magenta = new JButton(new ImageIcon(getClass().getResource("/images/magenta_opt.png")));
        magenta.addActionListener(aoe);
        
        setSpeed = new JButton("Set Speed");
        setSpeed.addActionListener(aoe);
                
        labelInstruction = new JLabel("<html>Create your exercise here. <br>You can change the turtle mode or restart if you change your mind. <br>Click on the buttons to create a drawing for your pupils to redo.</html>");
        labelMode = new JLabel("Change Turtle Mode:");
        
        // instanciation of panels
        // label panels
        panelArrows = new JPanel();
        panelArrows.setLayout(new GridLayout(3,3));
        panelArrows.add(myEmptyLabel = new JLabel());
        panelArrows.add(forward);
        panelArrows.add(myEmptyLabel = new JLabel());
        panelArrows.add(left);
        panelArrows.add(move);
        panelArrows.add(right);
        panelArrows.add(myEmptyLabel = new JLabel());
        panelArrows.add(backward);
        panelArrows.add(myEmptyLabel = new JLabel());
        
        panelLabel = new JPanel();
        panelLabel.setLayout(new GridLayout(2,1));
        panelLabel.add(labelInstruction);
        panelLabel.add(labelMode);
        
        panelMode = new JPanel();
        panelMode.setLayout(new GridLayout(4,1));
        panelMode.add(normal);
        panelMode.add(color);
        panelMode.add(fast);
        panelMode.add(restart);
        
        panelButtonsRight = new JPanel();
        panelButtonsRight.setLayout(new GridLayout(2,2));
        panelButtonsRight.add(speedUp);
        panelButtonsRight.add(slowDown);
        panelButtonsRight.add(write);
        panelButtonsRight.add(unwrite);
        
        panelRight = new JPanel();
        panelRight.setLayout(new GridLayout(5,1));
        panelRight.add(panelLabel);
        panelRight.add(panelMode);
        panelRight.add(panelButtonsRight);
        panelRight.add(panelArrows);
        panelRight.add(save);
        
        myFrame = new JFrame();
        canv = Canvas.getCanvasPanel();
        myFrame.add(canv, BorderLayout.CENTER);
        myFrame.add(panelRight, BorderLayout.EAST);
        
        //myFrame = new JFrame("Create Exercise");//give the name to the frame
        myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //kill the application when we close the window

            
        myFrame.setVisible(true);
        myFrame.pack();
        
        if (ex.getModeC() != null){
            chooseMode(colorTurtle);
        }else if (ex.getModeR() != null){
            chooseMode(fastTurtle);
        }
    }
    

    
}
